# Перечисленны разрешенные (актуальные) версии TLS для установки HTTPS-соединения
#ssl_protocols TLSv1.2 TLSv1.3;

# Выбор используемого шифрования определяет сервер, а не клиент
#ssl_prefer_server_ciphers on;

# Списко разрешенных шифров для TLSv1.2 (Для TLSv1.3 - не применяется)
ssl_ciphers 'EECDH+AESGCM:EECDH+CHACHA20:EECDH+AES256';

# Активация HSTS (всегда использовать HTTPS при образении к сайту): срок действия 2 года, распространяется на поддомены *.anydomain.ru
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

# Запрещает отображение сайта во встроенном iframe. (Защита от clickjacking-атак)
add_header X-Frame-Options "DENY" always;

# Запрещает браузеру определять MIME-тип самостоятельно. (Предотвращает MIME-type sniffing)
add_header X-Content-Type-Options "nosniff" always;

# Включает встроенную XSS-защиту в браузерах.
add_header X-XSS-Protection "1; mode=block" always;

# Кэшировать SSL-сессию
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;

# сократить время установления SSL (OCSP)
#ssl_stapling on;
#ssl_stapling_verify on;
